version: 2
jobs:
  build:
    docker:
      - image: wecs/circle-ci-gcloud-node:0.1.0
    working_directory: ~/workspace
    environment:
      DEPLOYMENT_NAME: my-first-cluster-122
      PROJECT_ID: circlecitest-282416
      CLUSTER_NAME: my-first-cluster-1
      CLUSTER_NAME_STAG: my-first-cluster-1-stag
      CLOUDSDK_COMPUTE_ZONE: us-central1-c 
      CONTAINER_NAME: my-first-cluster-1
      IMAGE: my-first-cluster-1
      REG_ID: my-first-cluster-1
      REG_ID_PROD: my-first-cluster-1-prod
      IMG_TAG: 0.1.0
      PROJECT_NAME: my-first-cluster-1
      DEPLOYMENT_ENVIRONMENT: staging
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install node packages
          command: |
            npm install
      
      - run:
          name: Start app
          command: |
            npm start &
      - run:
          name: Run tests
          command: |
            npm test
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run:
          name: Build and Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sh ./deployment.sh
            fi 